### ISSUE TITLE
Error executing test-operators.py

### ISSUE THREAD

**Issue by torrentalle** [SpiderLabs/secrules-language-evaluation#1]
When I try to execute test-operators.py I get this error
From where can I get the `sec_utils` module?

``` python
Traceback (most recent call last):
  File "E:/Albert/Desenvolupament/PHP/www/secrules-language-evaluation/test-operators.py", line 8, in <module>
    from seclang.sec_parser import sec_operator
  File "E:\Albert\Desenvolupament\PHP\www\secrules-language-evaluation\seclang\sec_parser.py", line 7, in <module>
    from sec_core import *
  File "E:\Albert\Desenvolupament\PHP\www\secrules-language-evaluation\seclang\sec_core.py", line 6, in <module>
    from sec_operator import *
  File "E:\Albert\Desenvolupament\PHP\www\secrules-language-evaluation\seclang\sec_operator.py", line 6, in <module>
    from sec_utils import *
ImportError: No module named sec_utils
```

**Comment by torrentalle** [comment]
It's working now.
Thank's
